[build]
  publish = "/"
  command = ""

[build.environment]
  NODE_VERSION = "20"

[image]
  name = "ubuntu/jammy"

[context.master]
  command = "pnpm build"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"